#!/bin/bash

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Install devtools if not already installed
Rscript -e "if (!require('devtools', quietly = TRUE)) install.packages('devtools', repos='https://cran.rstudio.com/')"

# Install package dependencies
Rscript -e 'devtools::install_deps(dependencies = TRUE)'
