# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_minPartyDistance_wrappers", use_symbols = TRUE, package_name = "minPartyDistance")

#' @usage NULL
#' @useDynLib minPartyDistance, .registration = TRUE
NULL

#' Midpoint-based approach to computing expected distance to nearest party
#'
#' This divides the voter space into segments between party midpoints,
#' then integrates the expected distance to the nearest party in each segment.
#' @export
mean_min_abs_distance_midpoints <- function(parties) .Call(wrap__mean_min_abs_distance_midpoints, parties)

#' Given an array of voter positions and party positions,
#' computes the mean of the minimum absolute distances from each voter to the nearest party.
#' @export
mean_min_abs_distance <- function(voters, parties) .Call(wrap__mean_min_abs_distance, voters, parties)

#' Monte Carlo simulation entirely in Rust for fair benchmarking
#' Runs multiple simulations and returns the mean result
#' @export
mean_min_abs_distance_mc_batch <- function(parties, n_voters, n_simulations, seed) .Call(wrap__mean_min_abs_distance_mc_batch, parties, n_voters, n_simulations, seed)


# nolint end
